Play travis
Otus-DevOps-2020-11/m013_infra pull request #1
Opened 2020-12-21 19:12 UTC by m013

2020-12-22 05:54 UTC, mrgreyves requested changes
Здравствуйте! Проверил ваше дз. Нужно внести правки. Сообщения в слак отправляются?

2020-12-22 05:54 UTC, mrgreyves commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
Вот тут нужно пофиксить

2020-12-22 15:54 UTC, m013 commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
здравствуйте
оповещения приходят
![image](https://user-images.githubusercontent.com/37451707/102907394-0b8d1080-4487-11eb-9a00-2d3e33a60794.png)

ниже сделал коммит 
fixed test.py

2020-12-23 13:33 UTC, mrgreyves approved these changes
Здравствуйте!) Проверил ваше дз. Не забывайте добавлять описание к вашим пр.

2020-12-23 13:33 UTC, mrgreyves commented on .travis.yml
> +dist: trusty
Проверьте на всякий случай этот файл на корректность

2021-04-04 17:52 UTC, merged